export const titleHead= {
  aboutTitle: "About",
  aboutSubTitle: "Find more about us",
  serviceTitle: "Services",
  serviceSubTitle: "Check our services",
  portfolioTitle: "portfolio",
  portfolioSubTitle: "Check our portfolio",
  careerTitle: "Career",
  careerSubTitle: "Find Job  in our career page",
  contactTitle: "Contact",
  contactSubTitle: "Contact Us",
  blogTitle: "Blog",
  blogSubTitle: "Read our latest Blog",
  todoTitle: "to do List",
  todoSubTitle: "Find to do list here",
};